dist: xenial
language: scala
  - 2.12.12
jdk:
  - openjdk11
script:
  - sbt ++$TRAVIS_SCALA_VERSION clean compile
  - sbt ++$TRAVIS_SCALA_VERSION coverage test coverageReport
  - sbt ++$TRAVIS_SCALA_VERSION assembly
deploy:
  provider: releases
  api_key:
    secure: QAgp1rqWRm8FhlW8KI9yhKeBVNOy/hxHmkr3W8K3Mj5dSfZkNHrmMm4w8BHlOYhcozs7NQJ/Vnp7SGUOm0Z7IiMBZ5c6eY/3yov+fu91tAbU85MFah8jMAu2ixMQNksKQQe8vjquIdD1SQGIEE77C0hVN9xcmBfLvlkp5VQdLEB/811XSQxAZJSxpr0i4FP94bghHxPmZfpD3bRsbJiUwoYQudVwRwBZJNJM9a7v2Jd7aTNZBLk7BHh8is9a+1xi9mCsGExbVuSiI5SFQRoWiM3uizgfjYRMAxfimUG+VLk5QNrA+kVjVTC9ecwFdHX9cWjhxI/LrZaNUHIhJkrsj2Aio6n3NZEcO0RDn4/tSv2CErVyplcSwvoTYSndw56rLse7cOJVg5IoJlk7oAyGVHTwZFP5sazjgl9sBc++/DUbJ3OfBQu5smKkuFF1mCxSCGlWZBMMU/ZcaNgAeKvJDq33WlLATJFiWZZg2t1H+X9lcGnfou5szvndHx8qcgphwDUlD+x17nMFAI6rgwrtDA82IEwEBOTzsEqcwZGWVnIR9QuskmUPPeyIUI3XN17MpEulx3rmXfkwEv66c1Q8SHmCLiTSyJL2/JLZ0/EAtRHFkD4R8YJ2nq6D75BStMmyCtGOKvd3j5m2Um273BcwRDOHadq/ovHrXZIDD92Fin8=
  file_glob: true
  file:
    - "target/scala-2.12/io-opentargets-etl-literature-assembly-*"
  on:
    repo: opentargets/platform-etl-literature
    tags: true
    all_branches: false
  skip_cleanup: true
after_success:
  - bash <(curl -s https://codecov.io/bash)
